### ISSUE TITLE
GetFilteredTransaction Expecting Value

### ISSUE THREAD

**Issue by bNTGeez** [apache/incubator-resilientdb-graphql#3]
We tried testing the GetFilteredTransaction from the blogpost on the cloud Strawberry GraphQL. After running it, we run into the error of 
""message": "Expecting value: line 1 column 747 (char 746)",". We went into the discord to get help from @kaustubhKVS  We tried getting around the error by getting an owner and recipient public key by generating a key, setting the transaction, and getting the transaction to get working public keys. Even after entering public keys, we end up with an error 
" "message": "Expecting value: line 1 column 747 (char 746)",". 

After putting in the owner and recipient public key, we expected to get a list of data between the two users. 

![image](https://github.com/ResilientApp/ResilientDB-GraphQL/assets/72530493/00b2c788-ae93-4d5a-975f-b2a5edd7ffd6)
![image](https://github.com/ResilientApp/ResilientDB-GraphQL/assets/72530493/3de2a74a-afcf-404b-8fab-7cbe14526a73)

@apratimshukla6 @kaustubhKVS

**Comment by apratimshukla6** [comment]
The issue was caused due to a bug in parsing the JSON data after single characters had been committed to ResilientDB via the command line. This issue has now been resolved via regex and pulling the latest commit will fix it.
